# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

center <- function(M) {
    .Call('mbereg_center', PACKAGE = 'mbereg', M)
}

mycov <- function(M1, M2) {
    .Call('mbereg_mycov', PACKAGE = 'mbereg', M1, M2)
}

foo <- function(z) {
    .Call('mbereg_foo', PACKAGE = 'mbereg', z)
}

testy <- function(y, Tobs, z) {
    .Call('mbereg_testy', PACKAGE = 'mbereg', y, Tobs, z)
}

