# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

center <- function(M) {
    .Call('mbereg_center', PACKAGE = 'mbereg', M)
}

mycov <- function(M1, M2) {
    .Call('mbereg_mycov', PACKAGE = 'mbereg', M1, M2)
}

SS <- function(v) {
    .Call('mbereg_SS', PACKAGE = 'mbereg', v)
}

SS_neg <- function(v) {
    .Call('mbereg_SS_neg', PACKAGE = 'mbereg', v)
}

sqrtm_cpp <- function(M) {
    .Call('mbereg_sqrtm_cpp', PACKAGE = 'mbereg', M)
}

cov2cor_cpp <- function(V) {
    .Call('mbereg_cov2cor_cpp', PACKAGE = 'mbereg', V)
}

foo <- function(M) {
    .Call('mbereg_foo', PACKAGE = 'mbereg', M)
}

bar <- function(v) {
    .Call('mbereg_bar', PACKAGE = 'mbereg', v)
}

testy <- function(y, Tobs, z, normal_draws) {
    .Call('mbereg_testy', PACKAGE = 'mbereg', y, Tobs, z, normal_draws)
}

testFunctor <- function(x) {
    .Call('mbereg_testFunctor', PACKAGE = 'mbereg', x)
}

